name: workflow2

on: 
  # push:
  #   branches: [ "main" ]

  workflow_dispatch:

jobs:
          
  reusable_workflow_job:
    uses: pinkesh-ceq/Resusable-called-wf/.github/workflows/blank.yml@main
    with:
      name: pinkesh
    secrets:
      inherit


